---
- name: Lets look at some disks
  hosts: all
  become: true
  gather_facts: false
  ignore_errors: true
  vars_prompt:
         - name: var_pvs
           prompt: "Select the disk that appears in disk.stdout"
           private: no
  tasks:

         - name: create vg
           lvg:
              vg: vgdata
              pvs: "{{ var_pvs }}"

         - name: create lvm
           lvol:
              vg: vgdata
              lv: lvdata
              size: 100%FREE

         - name: create filesystem
           filesystem:
                    fstype: ext4
                    dev: /dev/vgdata/lvdata

         - name: mount lvm
           mount:
                fstype: ext4
                src: /dev/vgdata/lvdata
                path: /data/brick1/pv
                state: mounted