---
- name: install packages and add docker repo
  hosts: all
  tasks:
        - name: Add docker-ce.repo
          command: "dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
        
        - name: install required packages
          yum:
              name: '{{ item }}'
              state: latest
          with_items:
              - dnf-utils
              - epel-release
              - vim
              - nano
              - cockpit
              - ansible
              - net-tools
              - lvm2
              - htop
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - centos-release-gluster9
              - glusterfs
              - glusterfs-libs
              - glusterfs-server
