---
- name: check docker status
  hosts: all
  gather_facts: true
  tasks:
        - name: Activate docker
          shell: . /root/iaac-codes/status-docker.sh
          register: script_local
          when: ansible_host == "localhost"

        - debug:
                var: script_local

        - name: copy script to remote hosts
          copy:
              src: /root/iaac-codes/status-docker.sh
              dest: /root/scripts-from-master-node/
              owner: root
              group: root
              mode: "0755"
          when: ansible_host != "localhost"

        - name: execute script
          shell: ". /root/scripts-from-master-node/status-docker.sh"
          register: status_docker
          when: ansible_host != "localhost"

        - debug:
                var: status_docker